from typing import Protocol

from uuid import UUID

from ..schemas import Page, Pagination
from .entities import Entity


class Repository[EntityT: Entity](Protocol):

    async def create(self, entity: EntityT) -> EntityT: ...

    async def read(self, uid: UUID) -> EntityT | None: ...

    async def paginate(self, params: Pagination) -> Page[EntityT]: ...

    async def update(self, uid: UUID, **kwargs) -> EntityT: ...

    async def upsert(self, entity: EntityT) -> None: ...

    async def delete(self, uid: UUID) -> None: ...

    async def exists(self, uid: UUID) -> bool: ...

    async def get_by_ids(self, ids: list[UUID]) -> list[EntityT]: ...
