"""edit counterparty products

Revision ID: a8458c5585e7
Revises: 717610c0cd9e
Create Date: 2026-05-03 19:16:38.755583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8458c5585e7'
down_revision: Union[str, Sequence[str], None] = '717610c0cd9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('counterparty_products', 'is_primary')
    op.drop_column('counterparty_products', 'linked_by')
    op.drop_column('counterparty_products', 'environment')
    op.drop_column('counterparty_products', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counterparty_products', sa.Column('status', postgresql.ENUM('ACTIVE', 'SUSPENDED', 'ARCHIVED', name='counterpartyproductstatus'), autoincrement=False, nullable=False))
    op.add_column('counterparty_products', sa.Column('environment', postgresql.ENUM('PRODUCTION', 'STAGING', 'DEVELOPMENT', 'TESTING', name='environmenttype'), autoincrement=False, nullable=False))
    op.add_column('counterparty_products', sa.Column('linked_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('counterparty_products', sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
