"""rename assignee tickets

Revision ID: 1eaf72f310c5
Revises: a8458c5585e7
Create Date: 2026-05-12 12:59:14.539064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1eaf72f310c5'
down_revision: Union[str, Sequence[str], None] = 'a8458c5585e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_membership', 'project_memberships', ['project_id', 'user_id'])
    op.drop_column('project_memberships', 'removed_at')
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index('ix_project_key', 'projects', ['key'], unique=False)
    op.add_column('tickets', sa.Column('assignee_id', sa.Uuid(), nullable=True))
    op.drop_column('tickets', 'assigned_to')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('assigned_to', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_column('tickets', 'assignee_id')
    op.drop_index('ix_project_key', table_name='projects')
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('project_memberships', sa.Column('removed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint('uq_membership', 'project_memberships', type_='unique')
    # ### end Alembic commands ###
