"""add null uq_tasks

Revision ID: 84669aafe84b
Revises: 9b9bbd59836d
Create Date: 2026-05-25 15:59:26.499380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84669aafe84b'
down_revision: Union[str, Sequence[str], None] = '9b9bbd59836d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_task_sequences'), 'tasks_sequences', type_='unique')
    op.create_unique_constraint('uq_task_sequences', 'tasks_sequences', ['project_id', 'ticket_id'], postgresql_nulls_not_distinct=True)
    # ### planned_end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_task_sequences', 'tasks_sequences', type_='unique')
    op.create_unique_constraint(op.f('uq_task_sequences'), 'tasks_sequences', ['project_id', 'ticket_id'], postgresql_nulls_not_distinct=False)
    # ### planned_end Alembic commands ###
